### ISSUE TITLE
Best practices for bots?

### ISSUE THREAD

**Issue by iliana** [docker-library/faq#13]
This is half "can we write a bot best practices document based on maintainer experience" and half "how do I write a bot for the amazonlinux images without making maintainers sad" issue :) The FAQ repo seems like a reasonable place for this to me.

* Do bots need to be listed as an image maintainer? (I assume yes, just as any other new maintainer needs to be listed.)
* What kind of information is useful in the PR title and description? (I've been opening PRs with no content because that requires human labor, but maybe I can teach a bot to be more useful than me!)
* Is it okay for two separate PRs to be open on the same image at once? (I ask because our infrastructure for building AL1 and AL2 execute separately, so if both are getting released at the same time it might generate two PRs unless I add some smarts around that.)
* What are some examples of well-behaving bots submitting official images PRs?

**Comment by tianon** [comment]
> Do bots need to be listed as an image maintainer? (I assume yes, just as any other new maintainer needs to be listed.)

Naw, we just ask that your bot includes the image maintainers in a comment so that you see any replies we might make without us having to ping you directly. :smile:

> What kind of information is useful in the PR title and description? (I've been opening PRs with no content because that requires human labor, but maybe I can teach a bot to be more useful than me!)

We have @docker-library-bot attempt to generate a list of commit links (and PR links, if it can), but it's not perfect.  That's for our users' sake, though -- for our review, we don't really care (since GitHub Actions will generate the diff that we actually review/care about).

> Is it okay for two separate PRs to be open on the same image at once? (I ask because our infrastructure for building AL1 and AL2 execute separately, so if both are getting released at the same time it might generate two PRs unless I add some smarts around that.)

It's "okay" but I would suggest caution -- we've got one particular maintainer who frequently makes two PRs concurrently and they very often result in merge conflicts because the files being changed are so short.  What I would recommend is using the same branch for both, if possible, and if you have it auto-open the PR have it comment instead if a PR already exists.

An alternative would be what we do for @docker-library-bot -- we have it do all the work to generate branches ready to make PRs, but we don't have it make the PRs themselves (because often our generate scripts will include noise or PRs we don't want to release yet or don't actually do anything like comment changes, so we filter the noise by hand).

We then periodically check branches on https://github.com/docker-library-bot/official-images to see if there are any pending and open them (if we determine they're appropriate to open).  You could instead have your automation send you link directly to the https://github.com/docker-library/official-images/compare/master...foo:bar?expand=1 of the branch it created so you know the automation kicked off and is ready for a PR to be opened.

> What are some examples of well-behaving bots submitting official images PRs?

The `nextcloud` bot is reasonably well-behaved: https://github.com/docker-library/official-images/pulls?q=is%3Apr+is%3Aclosed+author%3Atilosp-bot

(It only ever opens one PR at a time, it updates the PR at most once per day if it isn't merged already so we don't have a race during review, etc.)

The `node` PRs are OK, but do leave some things to be desired: https://github.com/docker-library/official-images/pulls?q=is%3Apr+is%3Aclosed+author%3Anodejs-github-bot

(For example, the titles are often poor since these are created automatically after a merge in their repo, and it will often open two PRs at once if two PRs merge downstream at the same time or before the previous PR has been reviewed.)

**Comment by tianon** [comment]
Closing as fixed via https://github.com/docker-library/faq/pull/18 :smile:
