### ISSUE TITLE
Multi stage Node.js build image for docker library

### ISSUE THREAD

**Issue by Aschen** [docker-library/faq#14]
I'm not sure to fully understand the condition explained here: https://github.com/docker-library/faq#multi-stage-builds

[This image](https://github.com/nodejs/docker-node/pull/1282) use an intermediary stage to build Node.js, can this build be considerate as "highly deterministic" ?

Please can you give your opinion on this matter? Thanks in advance.

**Comment by tianon** [comment]
When we talk about "highly deterministic" we mean it in the same sense as https://reproducible-builds.org/ -- multi-stage builds don't interact very nicely with the cache (that first build stage will be untagged, and thus not be preserved from an image pruning, which will then rebuild and cause a cache bust in the second stage unless the build artifacts are reproducible and thus still cache).

We would frankly discourage something like Node.js to be `FROM scratch` because it doesn't really provide a strong benefit to users over being `FROM alpine` (which is ~5MB and includes both a minimal shell _and_ a package manager).
